### ISSUE TITLE
Any updates on integrating this to chatllamacpp?

### ISSUE THREAD

**Issue by jsun57** [ThanhNguye-n/llamacpp_function_calling#1]
Hey! I am just wondering what's your plan for the PR on langchain in terms of timeline, as I am also trying to come up with good solutions to make chatllamacpp (hermes models) a proper tool-calling model (not the ReAct way, but with tool messages). Do not wanna reinvent the wheels here, and you have already had a plan!

**Comment by ThanhNguye-n** [comment]
@jsun

**Comment by ThanhNguye-n** [comment]
@jsun57 @rlancemartin  https://github.com/ThanhNguye-n/llamacpp_function_calling/blob/main/cookbook/langgraph.ipynb

the results is somehow like this. But still need to waiting an upcoming PR for chatllamacpp to compatible this version.

**Comment by jsun57** [comment]
> @jsun57 @rlancemartin https://github.com/ThanhNguye-n/llamacpp_function_calling/blob/main/cookbook/langgraph.ipynb
> 
> the result is somehow like this. But still need to waiting an upcoming PR for chatllamacpp to be compatible this version.
> 
> Because still have some remarkable bugs, I will fix when i'm free 😂.

Thanks for the quick update! May I know where you observed the critical bugs?

**Comment by ThanhNguye-n** [comment]
> Thanks for the quick update! May I know where you observed the critical bugs?

1. When using ChatLlamaCPP, the model generates unexpected tokens when my prompt is slightly long. This issue does not seem to occur with the original LlamaCPP Python deps.
2. Hermes-Pro running with ChatLlamaCPP is more "dumb" in tool calling compared to when it runs with LlamaCPP Python.

**Comment by jsun57** [comment]
Thanks! I just checked, how does the chat_handler parameter work? It's not in the ChatLlamaCPP class.

**Comment by ThanhNguye-n** [comment]
> Thanks! I just checked, how does the chat_handler parameter work? It's not in the ChatLlamaCPP class.

Yes, because I have not updated the code yet lol :) .

chat_handler is some kind of techinque to handle message input (such as message from role system, user, assistant,... something like that)
. More info please check on llamacpp python docs, I just take advantage of those params from them.

**Comment by jsun57** [comment]
I see. I guess for now the cookbook is not compatible with chatllamacpp yet! Looking forward to the updates then!
